### ISSUE TITLE
Error: Process completed with exit code 1 during Actions  (Exception in thread "main" java.lang.NullPointerException)

### ISSUE THREAD

**Issue by vmsavelyev** [jckleiner/notion-backup#19]
When I run actions it downs with error

22:15:08.776 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
22:15:09.082 [main] INFO com.greydev.notionbackup.NotionClient - Downloads will be saved to: /tmp/ 
22:15:09.083 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: markdown
22:15:09.083 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
22:15:09.083 [main] INFO com.greydev.notionbackup.NotionClient - Export comments: true
22:15:09.733 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
Exception in thread "main" java.lang.NullPointerException
	at com.greydev.notionbackup.NotionClient.getDownloadLink(NotionClient.java:213)
	at com.greydev.notionbackup.NotionClient.export(NotionClient.java:113)
	at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:65)
Error: Process completed with exit code 1.

**Comment by XeonraY-code** [comment]
I've been receiving the same error as of late.
The workspace export was triggered in Notion though, since I'm getting the "Your workspace export is ready" notification inside Notion itself and can manually download the .zip file.
The container did not download the export, probably because of the error which seems to pertain to getting the download link.

**Comment by jckleiner** [comment]
Do you see this error on each run or just sometimes? I could not reproduce the problem and I'm not sure why this happens. The export for my workspace seems to work fine.

I've added some more checks in #20, hopefully this will fix the export for you.

**Comment by XeonraY-code** [comment]
Hi

When I wrote my reply, the issue was on each run.
When my script ran again this weekend it did work for html, but not for markdown (I run both at same time to have the backup in 2 different formats).

I just ran it manually again and both attempts now worked. So I'm not sure if it is permantely fixed now or maybe a temporary issue with a slow response from notion?

**Comment by orellazri** [comment]
@jckleiner Unfortunately I started seeing this issue now as well (after it's been working for months)
```
08:32:09.404 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
08:32:09.802 [main] INFO com.greydev.notionbackup.NotionClient - DOWNLOADS_DIRECTORY_PATH is not set. Downloads will be saved to: /downloads
08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: html
08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Export comments: true
08:32:10.816 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
Exception in thread "main" java.lang.NullPointerException
        at com.greydev.notionbackup.NotionClient.getDownloadLink(NotionClient.java:235)
        at com.greydev.notionbackup.NotionClient.export(NotionClient.java:113)
        at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:65)
```

It looks like an export task is kicking off in Notion (I get an export notification), but the script fails nontheless

**Comment by Vvarbanov** [comment]
> @jckleiner Unfortunately I started seeing this issue now as well (after it's been working for months)
> 
> ```
> 08:32:09.404 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
> 08:32:09.802 [main] INFO com.greydev.notionbackup.NotionClient - DOWNLOADS_DIRECTORY_PATH is not set. Downloads will be saved to: /downloads
> 08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: html
> 08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
> 08:32:09.803 [main] INFO com.greydev.notionbackup.NotionClient - Export comments: true
> 08:32:10.816 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
> Exception in thread "main" java.lang.NullPointerException
>         at com.greydev.notionbackup.NotionClient.getDownloadLink(NotionClient.java:235)
>         at com.greydev.notionbackup.NotionClient.export(NotionClient.java:113)
>         at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:65)
> ```
> 
> It looks like an export task is kicking off in Notion (I get an export notification), but the script fails nonetheless

I have encountered the same issue and have noticed that `result.isSuccess()` changes to true but result.getStatus() is still null, causing the NPE.
This is why there is also no in_progress reporting in your log - the status is null and does not log any progress.

I am also getting the Notion export notification, and when I manually download the export, everything seems fine.

**Comment by nicholasdaviees** [comment]
I am also getting this same issue. It worked once but every time after that it has failed. 

```
02:16:20.408 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
02:16:20.815 [main] INFO com.greydev.notionbackup.NotionClient - Downloads will be saved to: /mnt/tank/apps/notion/ 
02:16:20.816 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: markdown
02:16:20.816 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
02:16:20.816 [main] INFO com.greydev.notionbackup.NotionClient - Export comments: true
02:16:21.333 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
Exception in thread "main" java.lang.NullPointerException
        at com.greydev.notionbackup.NotionClient.getDownloadLink(NotionClient.java:235)
        at com.greydev.notionbackup.NotionClient.export(NotionClient.java:113)
        at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:65)
```

**Comment by jckleiner** [comment]
Seems like Notion did some breaking changes to their API. The response JSON structure is completely different and they don't provide the `exportURL` in the response anymore (which was used to download the finished export).

I need to do some digging to find out if there is another way to get to the export URL.

**Comment by jckleiner** [comment]
The **problem seems to be on Notion's side**. The **workspace export** (not the single page export) does not work for me, it gets stuck:

<img width="379" alt="Screenshot 2025-01-12 at 17 48 36" src="https://github.com/user-attachments/assets/ced5af66-9274-4bbd-a487-b0f4aee40472" />

----


Note that there are 2 types of export events:
1. `exportBlock`: This **works**. It is triggered when you click the three dots on a page (on the upper right corner) and then click "Export" 
2. `exportSpace`: This **does not work** (at least for me). This is also what the `notion-backup` tool uses. This can be triggered by `Settings > Settings (under "Workspace") > "Export all workspace content"`

Meaning that there is nothing I can do to fix this at the moment. We need to wait and hope that the API gets fixed soon.

**Comment by Vvarbanov** [comment]
Manually exporting the workspace and using the script works for me.
The script has a different JSON response as you mentioned, but otherwise, the export itself works and has all the files inside for me:
![image](https://github.com/user-attachments/assets/33db970f-12f2-4582-ad67-af948a558ed0)

**Comment by natenjo** [comment]
> The **problem seems to be on Notion's side**. The **workspace export** (not the single page export) does not work for me, it gets stuck:
> 
> <img alt="Screenshot 2025-01-12 at 17 48 36" width="379" src="https://private-user-images.githubusercontent.com/27920157/402372339-ced5af66-9274-4bbd-a487-b0f4aee40472.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxOTk5MTQsIm5iZiI6MTczNzE5OTYxNCwicGF0aCI6Ii8yNzkyMDE1Ny80MDIzNzIzMzktY2VkNWFmNjYtOTI3NC00YmJkLWE0ODctYjBmNGFlZTQwNDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE4VDExMjY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZGU1MTU4NjZmYTc0NDFiMDU4N2E3ZDIwZDdhZjczMTEzYWU4M2RjODRlZTkyY2NiMTMxZTBhODIyNGYxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kBURqeik-cQk7A818peX_JGSFSGt9AIKLiti0ChmgIM">

I can confirm this, but I noticed while this was running I at some point I got the notification on my phone (where the notion app is also installed) "Your workspace export is ready".
But I did not get the email with the download link (which is mentioned in the screen) 
And the screen did not close.

Same behavour in the Windows-App and on the Web-App

**Comment by hbhargava7** [comment]
@natenjo I submitted a PR to the darobin-notion-backup repo with a fix. Looks like the exportSpace API no longer passes back the export link after finishing, so I scrape it from the getNotifications API instead.

https://github.com/darobin/notion-backup/pull/44

**Comment by jckleiner** [comment]
@hbhargava7 Your PR was really helpful, thanks for mentioning it here!

I've merged #22 (not the most robust implementation but it should do for now) and the export / backup works again now for my workspace. A new docker image with the changes have been uploaded.

Please let me know if this solved the problem for you as well so I can close this issue.

**Comment by clementmoulin** [comment]
Hi, I tried today after making a `docker compose pull`, did not worked.

I got the Notion notification about file being ready.
In logs I have:
```
notion-backup-1  | 11:15:19.905 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
notion-backup-1  | 11:15:20.502 [main] INFO com.greydev.notionbackup.NotionClient - DOWNLOADS_DIRECTORY_PATH is not set. Downloads will be saved to: /downloads
notion-backup-1  | 11:15:20.504 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: html
notion-backup-1  | 11:15:20.504 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
notion-backup-1  | 11:15:20.505 [main] INFO com.greydev.notionbackup.NotionClient - Export comments: true
notion-backup-1  | 11:15:21.460 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
notion-backup-1  | 11:15:26.896 [main] INFO com.greydev.notionbackup.NotionClient - The newest export trigger notification is still not in the Notion response. Trying again in 5 seconds...
[...]
notion-backup-1  | 11:17:45.765 [main] INFO com.greydev.notionbackup.NotionClient - The newest export trigger notification is still not in the Notion response. Trying again in 5 seconds...
notion-backup-1  | 11:17:51.135 [main] INFO com.greydev.notionbackup.NotionClient - Found a new export trigger notification in the Notion response. Attempting to extract the download URL. Timestamp of when the export was triggered: 1739186120505. Timestamp of the notification: 1739186267730
notion-backup-1  | 11:17:51.136 [main] INFO com.greydev.notionbackup.NotionClient - Download link extracted
notion-backup-1  | 11:17:51.136 [main] INFO com.greydev.notionbackup.NotionClient - Downloading file...
notion-backup-1  | 11:17:51.153 [main] INFO com.greydev.notionbackup.NotionClient - Downloaded export will be saved to: /downloads
notion-backup-1  | 11:17:51.154 [main] INFO com.greydev.notionbackup.NotionClient - fileName: notion-export-html_2025-02-10_11-17-51.zip
notion-backup-1  | 11:17:51.155 [main] INFO com.greydev.notionbackup.NotionClient - Downloading file to: '/downloads/notion-export-html_2025-02-10_11-17-51.zip'
notion-backup-1  | 11:17:51.974 [main] INFO com.greydev.notionbackup.NotionClient - Download finished: notion-export-html_2025-02-10_11-17-51.zip
notion-backup-1  | 11:17:51.976 [Thread-0] INFO com.greydev.notionbackup.NotionBackup - Both GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON and GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH are empty
notion-backup-1  | 11:17:51.984 [Thread-0] INFO com.greydev.notionbackup.NotionBackup - Skipping Google Drive upload. No secret provided for Google Drive.
notion-backup-1  | 11:17:51.976 [Thread-1] INFO com.greydev.notionbackup.NotionBackup - DROPBOX_ACCESS_TOKEN is blank. Trying to fetch an access token with the refresh token...
notion-backup-1  | 11:17:51.988 [Thread-1] INFO com.greydev.notionbackup.NotionBackup - Failed to fetch an access token. Either DROPBOX_REFRESH_TOKEN, DROPBOX_APP_KEY or DROPBOX_APP_SECRET is blank.
notion-backup-1  | 11:17:51.989 [Thread-1] INFO com.greydev.notionbackup.NotionBackup - No Dropbox access token available. Skipping Dropbox upload.
notion-backup-1  | 11:17:51.990 [Thread-3] INFO com.greydev.notionbackup.NotionBackup - Skipping pCloud upload. PCLOUD_ACCESS_TOKEN or PCLOUD_API_HOST is blank.
notion-backup-1  | 11:17:51.990 [Thread-2] INFO com.greydev.notionbackup.NotionBackup - Skipping Nextcloud upload. NEXTCLOUD_EMAIL, NEXTCLOUD_PASSWORD or NEXTCLOUD_WEBDAV_URL is blank.
```

But the "zip file" is actually a HTML file containing "Access denied! Please ask the owner to share the page with you [...]"

**Comment by jckleiner** [comment]
@clementmoulin I can confirm this, thank you.

Seems like a `file_token` is needed for authentication when downloading the ZIP from the extracted URL (see also https://github.com/jckleiner/notion-backup/pull/22).
Once you have the export URL, you can download it like the following with `curl` by providing the `file_token` cookie:
(`file_token` can be found in the Cookies tab in your browser after you log in to your account)

```bash
curl \
  -H "Cookie: file_token=..." \
  -O "https://file.notion.so/f/t/....zip"
```

What confuses me is that the export was downloaded yesterday via `notion-backup` (and the contents are my actual Notion pages) without the need of this `file_token`. That's why I didn't test the subsequent downloads. But now the "error page" is being downloaded as a ZIP file. Not sure how that first download succeeded.

I'll try to work on this soon, whenever I can find some time.

**Comment by Vvarbanov** [comment]
@jckleiner I looked into this again and found one fork that had already fixed this issue. I also implemented this into my own code, but I have made some other changes - updating Java to 21 and adding in Google Drive folders based on the year/month in my code.

The fix is a combination of those two commits:
- [Adding the token to the file download](https://github.com/jckleiner/notion-backup/commit/607375b9f4867e25d3bd1330db1eafe7f4097251)
- [Using the new `file_token` for downloading](https://github.com/jckleiner/notion-backup/commit/9551daa6e55c5b09a0e44ec7f4450802df865e54)

You can take a look at this fork for more details on the fix:
- https://github.com/daniel-shuy/notion-backup/blob/master/src/main/java/com/greydev/notionbackup/NotionClient.java

If you are interested in the Java update and Google Drive folders, you can also take a peek at my fork:
- https://github.com/Vvarbanov/notion-backup/blob/main/src/main/java/com/greydev/notionbackup/NotionClient.java

I could create a new fork that only contains the `file_token` fix if you don't have the time to fix this yourself right now.
Let me know your opinion and any concerns!

Thanks, credits, and kudos to @daniel-shuy for the fix.
