### ISSUE TITLE
Notion API workspace export returned a 'failure' state. Reason: User cannot access space, or it does not exist.

### ISSUE THREAD

**Issue by developerisnow** [jckleiner/notion-backup#9]
```
docker run \
    --rm=true \
    --env-file=.env \
    -v /Users/user/Downloads:/downloads \
    ghcr.io/jckleiner/notion-backup
20:15:07.289 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
20:15:07.604 [main] INFO com.greydev.notionbackup.NotionClient - DOWNLOADS_DIRECTORY_PATH is not set. Downloads will be saved to: /downloads 
20:15:07.605 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: markdown
20:15:07.605 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
20:15:08.329 [main] INFO com.greydev.notionbackup.NotionClient - taskId extracted
20:15:38.136 [main] INFO com.greydev.notionbackup.NotionClient - Notion API workspace export returned a 'failure' state. Reason: User cannot access space, or it does not exist.
20:15:38.137 [main] INFO com.greydev.notionbackup.NotionClient - downloadLink could not be extracted
Exception in thread "main" java.lang.IllegalStateException: Could not export notion file
        at com.greydev.notionbackup.NotionBackup.lambda$main$0(NotionBackup.java:57)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:57)
        ```

**Comment by japafrite** [comment]
Hello, token v2 is now an array like : v02%3Auser_token_or_cookies%3AviCNp4....VEd
Authentification is not working anymore

**Comment by fav0r-1t** [comment]
Am I true that there is no reason to make backup?

**Comment by ColeInc** [comment]
I'm recently getting a similar issue but it manages to extract tokenV2 but looks to fail on taskId:

Run java -jar ./target/notion-backup-1.0-SNAPSHOT.jar
03:04:13.882 [main] INFO com.greydev.notionbackup.NotionBackup - ---------------- Starting Notion Backup ----------------
INFO com.greydev.notionbackup.NotionClient - Downloads will be saved to: /tmp/ 
03:04:14.254 [main] INFO com.greydev.notionbackup.NotionClient - Using export type: markdown
03:04:14.254 [main] INFO com.greydev.notionbackup.NotionClient - Flatten export file tree: false
03:04:14.254 [main] INFO com.greydev.notionbackup.NotionClient - tokenV2 extracted
Exception in thread "main" java.lang.NullPointerException
	at com.greydev.notionbackup.NotionClient.triggerExportTask(NotionClient.java:218)
	at com.greydev.notionbackup.NotionClient.export(NotionClient.java:116)
	at com.greydev.notionbackup.NotionBackup.main(NotionBackup.java:56)
Error: Process completed with exit code 1.

**Comment by adrienjoly** [comment]
Same problem here: `User cannot access space` error, with credentials that look like that, after URL-decoding:

<img width="408" alt="image" src="https://github.com/jckleiner/notion-backup/assets/531781/c8e58709-3abf-47ad-af4d-da2b4b6d7363">

**Comment by jckleiner** [comment]
I unfortunately can't reproduce the above mentioned problems. I'm not sure if Notion did some changes or if it's specific to your use case.
Does anyone still get such errors? If so, please share a bit more information about how you are using the repository.

Also, using wrapping the values in `.env` with single quotes sometimes leads to problems.
